### ISSUE TITLE
1.17-1.4.1-FABRIC : Server crashes when attacking dummy

### ISSUE THREAD

**Issue by DentedPaz** [MehVahdJukaar/DuMmmMmmy1.16#4]
Thank you for making this, it works very well in single-player!  I get this server crash when attacking the dummy.

I think this is the relevant log section:
<details>
  <summary>Crash Log</summary>
  
[20:55:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_638
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity.showDamageDealt(TargetDummyEntity.java:485) ~[MmmMmmMmmMmm-1.17-1.4.1-FABRIC.jar:?]
	at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity.method_5643(TargetDummyEntity.java:477) ~[MmmMmmMmmMmm-1.17-1.4.1-FABRIC.jar:?]
	at net.minecraft.class_1657.method_7324(class_1657.java:1244) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java:1406) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244$1.method_34218(class_3244.java:1335) ~[intermediary-server.jar:?]
	at net.minecraft.class_2824$1.method_34213(class_2824.java:166) ~[intermediary-server.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1305) ~[intermediary-server.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[intermediary-server.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 24 more
[20:55:10] [Server thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:55:10] [Server thread/ERROR]: This crash report has been saved to: D:\_Minecraft\_Servers\_Home Server\.\crash-reports\crash-2021-11-29_20.55.10-server.txt
[20:55:10] [Server thread/INFO]: Stopping server
[20:55:10] [Server thread/INFO]: Saving players
[20:55:10] [Server thread/INFO]: Saving worlds
 
</details>

**Comment by MehVahdJukaar** [comment]
Oh damn I had another issue about this and totally forgot to fix. I'll try to publish an update with m some improvements soon

**Comment by MehVahdJukaar** [comment]
fixed
