### ISSUE TITLE
Server 'Crash' on hitting a dummy

### ISSUE THREAD

**Issue by 3e2j** [MehVahdJukaar/DuMmmMmmy1.16#5]
This may be a problem with lithium, no idea.
Modpack is Runedar 1.0.2
Server doesn't actually crash most likely due to 'not enough crashes'

```
[12:09:43] [Server thread/FATAL]: Error executing task on Server
net.minecraft.class_148: Lithium Class Analysis
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.2) ~[?:?]
        at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isMethodFromSuperclassOverwritten(ReflectionUtil.java:23) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        at me.jellysquid.mods.lithium.common.entity.EntityClassGroup$NoDragonClassGroup.lambda$static$0(EntityClassGroup.java:91) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        at me.jellysquid.mods.lithium.common.entity.EntityClassGroup.testAndAddClass(EntityClassGroup.java:77) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        at me.jellysquid.mods.lithium.common.entity.EntityClassGroup.contains(EntityClassGroup.java:60) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        at net.minecraft.util.collection.TypeFilterableList.localvar$bfg000$add(TypeFilterableList:540) ~[?:?]
        at net.minecraft.util.collection.TypeFilterableList.add(TypeFilterableList) ~[?:?]
        at net.minecraft.world.entity.EntityTrackingSection.add(EntityTrackingSection:25) ~[?:?]
        at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:171) ~[?:?]
        at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:161) ~[?:?]
        at net.minecraft.server.world.ServerWorld.addEntity(ServerWorld:852) ~[?:?]
        at net.minecraft.server.world.ServerWorld.spawnEntity(ServerWorld:803) ~[?:?]
        at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity.showDamageDealt(TargetDummyEntity.java:403) ~[MmmMmmMmmMmm-1.18-1.5.0-FABRIC.jar:?]
        at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity.setHealth(TargetDummyEntity.java:387) ~[MmmMmmMmmMmm-1.18-1.5.0-FABRIC.jar:?]
        at net.minecraft.entity.LivingEntity.applyDamage(LivingEntity:1637) ~[?:?]
        at net.minecraft.entity.LivingEntity.damage(LivingEntity:1099) ~[?:?]
        at net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity.damage(TargetDummyEntity.java:360) ~[MmmMmmMmmMmm-1.18-1.5.0-FABRIC.jar:?]
        at net.minecraft.entity.player.PlayerEntity.attack(PlayerEntity:1244) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.attack(ServerPlayerEntity:1439) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler$1.attack(ServerPlayNetworkHandler:1345) ~[?:?]
        at net.minecraft.class_2824$1.handle(class_2824.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.handle(PlayerInteractEntityC2SPacket:66) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractEntity(ServerPlayNetworkHandler:1315) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.apply(PlayerInteractEntityC2SPacket:53) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.apply(PlayerInteractEntityC2SPacket:13) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
        at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isMethodFromSuperclassOverwritten(ReflectionUtil.java:11) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        ... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
        at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isMethodFromSuperclassOverwritten(ReflectionUtil.java:11) ~[lithium-fabric-mc1.18.1-0.7.6.jar:?]
        ... 37 more
```

**Comment by MehVahdJukaar** [comment]
Yeah seems like a lithium problem with their reflection stuff

**Comment by MehVahdJukaar** [comment]
Should have been fixed
