### ISSUE TITLE
Crashing when putting onto dummy TF armor

### ISSUE THREAD

**Issue by makazuwr32** [MehVahdJukaar/DuMmmMmmy1.16#7]
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/21/22, 7:35 PM
Description: Rendering entity in world

java.lang.ClassCastException: class twilightforest.client.model.armor.FieryArmorModel cannot be cast to class net.mehvahdjukaar.dummmmmmy.client.TargetDummyModel (twilightforest.client.model.armor.FieryArmorModel is in module twilightforest@4.0.860 of loader 'TRANSFORMER' @32120956; net.mehvahdjukaar.dummmmmmy.client.TargetDummyModel is in module dummmmmmy@1.17-1.4.0 of loader 'TRANSFORMER' @32120956)
	at net.mehvahdjukaar.dummmmmmy.client.LayerDummyArmor.m_117125_(LayerDummyArmor.java:9) ~[MmmMmmMmmMmm-1.17-1.4.1.jar%2369!:1.17-1.4.0] {re:classloading}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_117118_(HumanoidArmorLayer.java:49) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:38) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:23) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:126) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:voidscape:entityalpha,xf:fml:voidscape:entityalpharendertype,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:voidscape:entityalpha,xf:fml:voidscape:entityalpharendertype,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(SourceFile:45) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(SourceFile:18) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:129) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1280) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1076) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:830) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2349!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.dummmmmmy.client.LayerDummyArmor.m_117125_(LayerDummyArmor.java:9) ~[MmmMmmMmmMmm-1.17-1.4.1.jar%2369!:1.17-1.4.0] {re:classloading}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_117118_(HumanoidArmorLayer.java:49) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:38) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:23) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:126) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:voidscape:entityalpha,xf:fml:voidscape:entityalpharendertype,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:voidscape:entityalpha,xf:fml:voidscape:entityalpharendertype,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(SourceFile:45) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(SourceFile:18) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,re:mixin}
-- Entity being rendered --
Details:
	Entity Type: dummmmmmy:target_dummy (net.mehvahdjukaar.dummmmmmy.entity.TargetDummyEntity)
	Entity ID: 535230
	Entity Name: Target Dummy
	Entity's Exact location: -4652.50, 74.00, 2876.50
	Entity's Block location: World: (-4653,74,2876), Section: (at 3,10,12 in -291,4,179; chunk contains blocks -4656,0,2864 to -4641,255,2879), Region: (-10,5; contains chunks -320,160 to -289,191, blocks -5120,0,2560 to -4609,255,3071)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: net.mehvahdjukaar.dummmmmmy.client.TargetDummyRenderer@30239525
	Location: 0.38,0.00,2.57 - World: (0,0,2), Section: (at 0,0,2 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.720024
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:129) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1280) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1076) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['makazuwr32'/535210, l='ClientLevel', x=-4652.88, y=74.00, z=2873.93]]
	Chunk stats: 729, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,77,176), Section: (at 0,13,0 in 8,4,11; chunk contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 95270193 game time, 108574401 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:676) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2384!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2349!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2338!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2283759104 bytes (2177 MiB) / 4601151488 bytes (4388 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20339.43
	Virtual memory used (MB): 12929.50
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 8.28
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.51, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Pirate Speak (The Seven Seas)
	CPU: 12x Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		torchmaster-3.0.1-beta.jar                        |Torchmaster                   |torchmaster                   |3.0.1-beta          |DONE      |Manifest: NOSIGNATURE
		ornamental-1.17.1-4.6.1.jar                       |Ornamental                    |ornamental                    |4.6.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.2.0.36.jar                           |Just Enough Items             |jei                           |8.2.0.36            |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.17.1-1.0.8.jar                   |Easy Villagers                |easy_villagers                |1.17.1-1.0.8        |DONE      |Manifest: NOSIGNATURE
		reap-1.17.1-1.0.0.jar                             |Reap Mod                      |reap                          |1.17.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		gaiadimension-1.17.1-1.3.4.jar                    |The Gaia Dimension            |gaiadimension                 |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.17.1-57.jar                           |Patchouli                     |patchouli                     |1.17.1-57           |DONE      |Manifest: NOSIGNATURE
		essentials-1.17.1-2.12.2.jar                      |Essentials                    |essentials                    |1.17.1-2.12.2       |DONE      |Manifest: NOSIGNATURE
		waystones-8.2.0+0.jar                             |Waystones                     |waystones                     |8.2.0+0             |DONE      |Manifest: NOSIGNATURE
		collective-1.17.1-3.0.jar                         |Collective                    |collective                    |3.0                 |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.17.1-7.0.10.jar                    |Clumps                        |clumps                        |7.0.10              |DONE      |Manifest: NOSIGNATURE
		tfrandoms-1.0.jar                                 |TF Random Features            |tfrandoms                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.17.1-1.9.2-forge.jar             |Nature's Compass              |naturescompass                |1.17.1-1.9.2-forge  |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.6.jar                           |WorldEdit                     |worldedit                     |7.2.6+4b2d1e7       |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.17.1-0.4.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |DONE      |Manifest: NOSIGNATURE
		balm-1.8.0+0.jar                                  |Balm                          |balm                          |1.8.0+0             |DONE      |Manifest: NOSIGNATURE
		Voidscape-1.17-0.2.11.jar                         |Voidscape                     |voidscape                     |1.17-0.2.11         |DONE      |Manifest: NOSIGNATURE
		The_Undergarden-1.17.1-0.6.1.jar                  |The Undergarden               |undergarden                   |0.6.1               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.17.1-0.13.0.131.jar         |Just Enough Resources         |jeresources                   |0.13.0.131          |DONE      |Manifest: NOSIGNATURE
		MelonMod-1.17.1-1.6.2.jar                         |Melon Golem                   |melongolem                    |1.17.1-1.6.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		PassthroughSigns-1.17.1-2.4.0.jar                 |Passthrough Signs             |passthroughsigns              |1.17.1-2.4.0        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.17.1-2.2.0.jar                |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.17-1.4.1.jar                       |MmmMmmMmmMmm                  |dummmmmmy                     |1.17-1.4.0          |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-26.jar                              |FastLeafDecay                 |fastleafdecay                 |26                  |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.17.1-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.17.1-v1           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		twilightforest-1.17.1-4.0.860-universal.jar       |The Twilight Forest           |twilightforest                |4.0.860             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.17.1-0.18.1.jar                 |Supplementaries               |supplementaries               |1.17.1-0.18.0       |DONE      |Manifest: NOSIGNATURE
		emojiful-1.17.1-3.0.0.jar                         |Emojiful                      |emojiful                      |1.17.1-3.0.0        |DONE      |Manifest: NOSIGNATURE
		chiselsandbits-1.1.39-ALPHA.jar                   |Chisels & bits                |chiselsandbits                |1.1.39-ALPHA        |DONE      |Manifest: NOSIGNATURE
		easy_piglins-1.17.1-1.0.2.jar                     |Easy Piglins                  |easy_piglins                  |1.17.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		selene-1.17.1-1.10.1.jar                          |Selene                        |selene                        |1.17.1-1.1          |DONE      |Manifest: NOSIGNATURE
		ironchest-1.17.1-12.0.2.jar                       |Iron Chests                   |ironchest                     |1.17.1-12.0.2       |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.17.1-0.1.2.116.jar           |Better Advancements           |betteradvancements            |0.1.2.116           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a1dc8bdb-9655-4efc-9ecd-a33f68f10a5f
	FML: 37.1
	Forge: net.minecraftforge:37.1.1

_____________________________________________________________________________________________________________________________________

I put fiery boots onto dummy and now it crashes my client on server.

**Comment by MehVahdJukaar** [comment]
this should have been fixed in 1.5.1
